chore(webapp): remove lyonjs assets
lyonjs/shortvid.io pull request #333
Opened 2023-05-24 13:56 UTC by Boyadjie

## 🤔 Why do you want to make those changes?

In order to detach the project from the LyonJS graphic identity, we want to modify the design to adapt it to the new colours

## 🧑‍🔬 How did you make them?

I added the monogram version of the new logo in the different colours and updated the colours on the pages (tested the contrast and it's valid AAA)

## 🧪 How to check them?

- check the colours on the preview

2023-05-24 14:31 UTC, Slashgear approved these changes

2023-05-25 08:43 UTC, CruuzAzul requested changes

2023-05-25 08:43 UTC, CruuzAzul commented on app/layout.tsx
> +		icon: '/Monogram-white.svg',
```suggestion
		icon: '/monogram-white.svg',
```

2023-05-25 08:43 UTC, CruuzAzul commented on styles/globals.css
> +	background-color: var(--purple-900);
The colour variables are not there to be used directly, you have to create other colour variables that use the base variables and have a specific purpose (e.g. background-color)

2023-05-25 13:07 UTC, CruuzAzul approved these changes
Is it not possible to change the colour of the JSON input outline ?

2023-05-25 15:30 UTC, merged