feat(theme): create theming for the app
lyonjs/shortvid.io pull request #375
Opened 2023-06-02 12:33 UTC by Boyadjie

## 🤔 Why do you want to make those changes?

To give the user the choice to choose it's favourite theme.

## 🧑‍🔬 How did you make them?

I've used the library next-theme and created a button to switch between theme light and dark, then i updated the app variables for the colours to match the theme.

## 🧪 How to check them?

- Check the preview and see if everything is ok
- Check the code

2023-06-02 14:03 UTC, Boyadjie commented on src/app/logo.tsx
> +			{theme === 'dark' && (
It's svg so you can set the image and change the colour with css variables

2023-06-05 07:15 UTC, Slashgear approved these changes

2023-06-08 13:43 UTC, CruuzAzul requested changes

2023-06-08 13:43 UTC, CruuzAzul commented on __test__/app/footer.test.tsx
> +		const copyright = screen.getByRole('copyright');
Ummmh c'est un rôle valide ça (sans qu'on l'ajoute) ? Je sais pas si au lieu de mettre un rôle à la main c'est pas plus propre dans ce cas de directement chercher le text

2023-06-08 13:43 UTC, CruuzAzul commented on public/branding/powered-by-vercel-black.svg
Peut-être pas dans branding, c'est pas lié directement à Shortvid.io

2023-06-08 13:43 UTC, CruuzAzul commented on src/app/ActiveLink.tsx
> +	const backgroundClassName = isActive ? 'bg-primary' : 'bg-btn-background';
bg = background ?
bg-btn-background = background button background ? 😅

2023-06-08 13:43 UTC, CruuzAzul commented on src/app/Footer.tsx
> +				)}
On a deux fois les mêmes composants là avec juste le lien de l'image qui change, je pense que l'on peut faire plus propre 😉

2023-06-08 13:43 UTC, CruuzAzul commented on src/app/Logo.tsx
> +export const Logo: React.FC<{className?: string}> = ({className}) => {
Ça serait pas mieux de passer que la couleur ? on pourra le target sans trop de problèmes même sans class

2023-06-08 13:43 UTC, CruuzAzul commented on src/app/RootLayout.tsx
> +'use client';
Retour à la ligne après, il faudra peut-être voir si il y a pas des règles eslint pour vérifier ces trucs là plutôt que de faire le même retour à chaque fois !

2023-06-08 13:43 UTC, CruuzAzul commented on src/app/forms/FontPicker.tsx
> +						background: '#eaeaea',
On peut pas utiliser une variable css pour ça ? Si on a besoin de cette couleurs plus tard pour d'autres inputs

2023-06-08 13:43 UTC, CruuzAzul commented on src/app/forms/input.tsx
> +					background: '#eaeaea',
Pareil ici 👈

2023-06-08 13:43 UTC, CruuzAzul commented on src/app/forms/inputDate.tsx
> +					background: '#eaeaea',
Pareil ici 👈

2023-06-08 13:43 UTC, CruuzAzul commented on src/app/forms/selectInput.tsx
> +					background: '#eaeaea',
Pareil ici 👈

2023-06-08 13:44 UTC, Slocaly requested changes

2023-06-08 13:44 UTC, Slocaly commented on src/app/forms/FontPicker.tsx
> +						background: '#eaeaea',
Ça ne vaudrai pas le coup d'en faire une variable ?

2023-06-08 13:44 UTC, Slocaly commented on src/app/SwitchThemeButton.tsx
> +			Switch to {theme === 'dark' ? 'light' : 'dark'} mode
Je pense que tu n'as pas besoin de ternaire ici ;)

2023-06-08 13:44 UTC, Slocaly commented on src/app/RootLayout.tsx
> +'use client';
C'est pas un peu dommage de mettre le composant Root en client ?

2023-06-08 13:44 UTC, Slocaly commented on src/app/Footer.tsx
> +				)}
Pour un peu moins de boilerplate, pourquoi ne pas juste conditionner l'attribut src ?

2023-06-08 13:44 UTC, Slocaly commented on styles/globals.css
> +	--logo: var(--purple-500);
Ça me parait un peu bizarre d'avoir des variables qui ne mentionne pas que ce sont des couleurs, quand on se retrouve dans le css ça n'est pas forcément clair je trouve, un petit `-color` à chaque fois me parait plus clair, à discuter

2023-06-08 13:44 UTC, Slocaly commented on src/app/NavBar.tsx
> +					<li className="text-btn-text text-center mt-2 md:mt-0 md:ml-5 py-2 px-4 rounded-lg cursor-pointer font-bold hover:scale-105">
Je trouve que cette classe n'est pas très claire

2023-06-08 13:54 UTC, Boyadjie commented on src/app/ActiveLink.tsx
> +	const backgroundClassName = isActive ? 'bg-primary' : 'bg-btn-background';
oui je savais pas comment les nommer 😭

2023-06-08 13:56 UTC, Boyadjie commented on src/app/Logo.tsx
> +export const Logo: React.FC<{className?: string}> = ({className}) => {
ba la couleur dépend d'une constante css passé par class. en passant la couleur on rajoute une condition de check du theme

2023-06-08 14:03 UTC, Boyadjie commented on styles/globals.css
> +	--logo: var(--purple-500);
Je vais chercher des good practice 👍

2023-06-08 14:51 UTC, Boyadjie commented on styles/globals.css
> +	--logo: var(--purple-500);
j'ai rajouter un color- devant chaque class c'est ce qui se fait bien, apres il y en a qui raccourcissent tout sur 2 caractères mais je suis pas fan, meme si c'est un peu verbeux c'est plus compréhensible. Sans oublier que les class tailwind vont disparaitre a terme

2023-06-08 15:08 UTC, Boyadjie commented on __test__/app/footer.test.tsx
> +		const copyright = screen.getByRole('copyright');
Je sais pas du tout je cherche 👍

2023-06-09 06:41 UTC, CruuzAzul approved these changes

2023-06-09 06:41 UTC, CruuzAzul commented on src/app/Footer.tsx
> +};
T'as pas besoin de créer un composant juste pour ça, tu pouvais juste mettre le `src` dans une constante c'était encore moins de ligne et moins de "complexité"

2023-06-09 06:41 UTC, CruuzAzul commented on src/app/Header.tsx
>  'use client';
Pourquoi on a mis ça en client component ? On peut changer ?

2023-06-09 06:41 UTC, CruuzAzul commented on styles/app/inputs/button.module.css
On peut pas mettre tout ça dans un dossier `common` plutôt que `inputs` ? Ça fera le dossier des styles globaux à l'app

2023-06-09 06:46 UTC, Boyadjie commented on src/app/RootLayout.tsx
> +'use client';
Vu que c'est assez spécifique j'ai rien trouvé dans la doc, et en cherchant sur des articles et autres j'ai juste vu comment créer des règles eslint custom mais c'est compliqué pour pas grand chose je trouve

2023-06-09 14:03 UTC, Slocaly approved these changes

2023-06-09 14:03 UTC, Slocaly approved these changes

2023-06-09 14:39 UTC, merged