feat(theme): updated theme button switch
lyonjs/shortvid.io pull request #382
Opened 2023-06-05 13:59 UTC by Boyadjie

## 🤔 Why do you want to make those changes?

To switch theme, it's good with a basic button that update the text, it's better with icons.

## 🧑‍🔬 How did you make them?

I created a group of buttons with icons that represent the different themes (and the default system one) based on the design from Vercel :
<img width="120" alt="Screenshot 2023-06-05 at 15 57 19" src="https://github.com/lyonjs/shortvid.io/assets/72607059/a42522cb-b7e0-4b56-b3dc-6fab0c406bb5">

## 🧪 How to check them?

- Check the preview and test the component
- Read the code

2023-06-06 09:53 UTC, Boyadjie commented
I'm not sure about the position on the footer, maybe do it like that is better ? IDK
<img width="1153" alt="Screenshot 2023-06-06 at 11 52 04" src="https://github.com/lyonjs/shortvid.io/assets/72607059/d4a8dbf7-bbd0-4abc-884c-c5831c23821b">

2023-06-06 12:15 UTC, Slashgear approved these changes

2023-06-06 12:15 UTC, Slashgear commented on __test__/app/inputs/SwitchThemeButton.test.tsx
> +		expect(darkButton.getAttribute('aria-checked')).toEqual('false');
```suggestion
		expect(systemButton).toBeChecked();
		expect(lightButton).toBeChecked();
		expect(darkButton).toBeChecked();
```

Same for above

2023-06-09 06:58 UTC, CruuzAzul requested changes

2023-06-09 06:58 UTC, CruuzAzul commented on styles/globals.css
> +	--switch-border: rgba(255, 255, 255, 0.4);
Il y a pas des problèmes de contrast là ? 👀

2023-06-09 06:58 UTC, CruuzAzul commented on styles/globals.css
> +	--switch-border: #e0e0e0;
Là il y a des couleurs en #xxxx on peut pas soit utiliser des couleurs du thèmes ou alors en ajouter une si on les utilise plusieurs fois ?

2023-06-09 06:58 UTC, CruuzAzul commented on src/app/Footer.tsx
> +			<div className={styles.bottomFooter}>
```suggestion
			<div className={styles.bottomBar}>
```

2023-06-09 06:58 UTC, CruuzAzul commented on src/app/SwitchThemeButton.tsx
> +}> = ({themeLabel, themeValue, handleSelectTheme, isChecked, iconifyId}) => {
On peut pas extraire ça dans un type, ca va alléger le composant

2023-06-09 06:58 UTC, CruuzAzul commented on src/app/SwitchThemeButton.tsx
> +			/>
```suggestion
			<ThemeRadioButton
				isChecked={selectedTheme === 'dark'}
				handleSelectTheme={handleSelectTheme}
				themeLabel="dark"
				themeValue="dark"
				iconifyId="ph:moon"
			/>
			<ThemeRadioButton
				isChecked={selectedTheme === 'system'}
				handleSelectTheme={handleSelectTheme}
				themeLabel="system"
				themeValue={systemTheme}
				iconifyId="gg:screen"
			/>
			<ThemeRadioButton
				isChecked={selectedTheme === 'light'}
				handleSelectTheme={handleSelectTheme}
				themeLabel="light"
				themeValue="light"
				iconifyId="ph:sun"
			/>
```

2023-06-09 06:58 UTC, CruuzAzul commented on src/app/SwitchThemeButton.tsx
> +			/>
En plus on devrait pouvoir utiliser la même valeur pour la valeur du thème dans `isChecked` et `themeLabel` non ?

2023-06-09 06:58 UTC, CruuzAzul commented on src/app/SwitchThemeButton.tsx
> +		}
On set dans le local storage que si c'est le theme system ?

2023-06-09 06:58 UTC, CruuzAzul commented on src/app/SwitchThemeButton.tsx
> +	const [selectedTheme, setSelectedTheme] = useState<string>('system');
Pourquoi on a besoin de ce state ? On a pas le theme dans le hook ?

2023-06-09 07:11 UTC, Boyadjie commented on src/app/SwitchThemeButton.tsx
> +		}
oui en fait la lib va set automatiquement en local storage mais uniquement les valeurs 'dark' et 'light' donc il faut manuellement set le system. C'est du au fait qu'on ne puisse pas faire `setTheme('system)`, en faisant ça on aurais bien system en local storage mais le switch de theme ne se ferais pas niveaux css. 

Ce qui est possible par contre c'est de faire un hook `setSelectedTheme` qui se chargerais de faire `setTheme` et de set le localStorage pour system

2023-06-09 07:12 UTC, Boyadjie commented on src/app/SwitchThemeButton.tsx
> +	const [selectedTheme, setSelectedTheme] = useState<string>('system');
c'est lié à la question juste au dessus

2023-06-09 07:54 UTC, Slocaly requested changes

2023-06-09 07:54 UTC, Slocaly commented on src/app/SwitchThemeButton.tsx
> +			/>
Vu toutes les props que tu passe, je ne sais pas si un composant custom est nécessaire ici, à discuter

2023-06-09 07:56 UTC, Slocaly commented on src/app/SwitchThemeButton.tsx
> +		}
Je pense qu'il faut le plus possible abstraire les accès au local Storage dans les composant, ça me paraîtrait logique d'avoir toute la gestion du thème dans un hook

2023-06-12 13:25 UTC, Slocaly requested changes

2023-06-12 13:25 UTC, Slocaly commented on __test__/app/footer.test.tsx
> +		});
Pourquoi mocker le theme ici ? Je ne pense pas que ton test en dépend

2023-06-12 13:25 UTC, Slocaly commented on __test__/app/hooks/useSelectedTheme.test.tsx
> +		});
Tu peux definir une fonction de render à la racine du describe pour ne pas avoir à la réécrire partout : 

```js
const renderSelectedThemeHook = () => renderHook(() => useSelectedTheme(), {
	wrapper: ({children}) => (
		<CustomeThemeProvider>{children}</CustomThemeProvider>
	)	
});

it('', () => {
	const { result } = renderSelectedThemeHook();
})
```

2023-06-12 13:25 UTC, Slocaly commented on setup-jest.js
Je ne pense pas que tu ai besoin du `beforeAll`, ton setup est executé avant les test ton mock sera donc actif

2023-06-12 13:25 UTC, Slocaly commented on setup-jest.js
J'ajouterai bien un petit commentaire pour expliquer que le mock est nécessaire à cause d'un manque dans la lib `JsDom`, avec un petit lien pour bien comprendre

2023-06-12 13:25 UTC, Slocaly commented on src/app/Footer.tsx
> +				<span role="copyright">
On a toujours le role copyright ?

2023-06-12 13:25 UTC, Slocaly commented on src/app/SwitchThemeButtons.tsx
> +	const {selectedTheme, setSelectedTheme} = useSelectedTheme();
Tu utilise `useTheme` dans `useSelectedTheme`, ça ne me parait pas déconnant que tu puisse récupérer directement le `systemTheme` depuis `useSelectedTheme`

2023-06-12 13:25 UTC, Slocaly commented on src/app/SwitchThemeButtons.tsx
> +	const {selectedTheme, setSelectedTheme} = useSelectedTheme();
On a peut être pas besoin de récupérer le thème ici si on ne fait que l'envoyer au composant enfant

2023-06-12 13:25 UTC, Slocaly commented on src/app/SwitchThemeButtons.tsx
> +export type SelectedThemeTypes = 'dark' | 'light' | 'system';
Je ne sais pas si c'est le bon endroit pour mettre ce type sachant qu'on ne l'utilise pas directement, peut être dans le hook qu'en pense tu ?

2023-06-12 13:25 UTC, Slocaly commented on src/app/hooks/useSelectedTheme.ts
> +	const [themeName, setThemeName] = useState<string>('default');
On veux toujours le nom 'default' par défaut ? pas `undefined` ?

2023-06-12 14:22 UTC, Boyadjie commented on src/app/SwitchThemeButtons.tsx
> +	const {selectedTheme, setSelectedTheme} = useSelectedTheme();
C'est mieux de le faire ici, ça évite d'appeler le hook 3 fois.

2023-06-12 14:22 UTC, Boyadjie commented on src/app/hooks/useSelectedTheme.ts
> +	const [themeName, setThemeName] = useState<string>('default');
on peut mettre undefined ça fait moins de code

2023-06-14 07:32 UTC, CruuzAzul approved these changes

2023-06-14 07:32 UTC, CruuzAzul commented on src/app/hooks/useSelectedTheme.ts
> +		}
```suggestion
	setThemeName(theme === 'system' ? systemTheme : theme);
```

2023-06-14 07:51 UTC, Boyadjie commented on styles/app/common/themeRadioGroup.module.css
> +
tu veux rajouter quoi ? le background ?

2023-06-14 08:18 UTC, Slocaly approved these changes

2023-06-14 09:03 UTC, CruuzAzul commented on src/app/ThemeRadioButton.tsx
> +	};
On peut pas directement mettre cette condition dans une constante ?

2023-06-14 12:08 UTC, merged