feat(app): add thumbnail to sidebar nav
lyonjs/shortvid.io pull request #391
Opened 2023-06-30 12:17 UTC by Boyadjie

## 🤔 Why do you want to make those changes?

To enhance the navigation and make the videos more recognisable in it.

## 🧑‍🔬 How did you make them?

I've created a config flies for the videos and a hook that link it with the nav config. Then i displayed a remotion Thumbnail instead of juste the title and added the time in seconds of the videos in the nav.

## 🧪 How to check them?

- Check the code
- Check the preview

2023-07-04 17:04 UTC, CruuzAzul requested changes

2023-07-04 17:04 UTC, CruuzAzul commented on src/data/compositionsList.ts
> +import {staticFile} from 'remotion';
Il nous manque peut-être une règle de lint pour ça mais l'ordre des import est pas dingue, il faudrait que l'on ai en premier les imports des trucs de lib, puis après de nos fichiers à nous !

2023-07-04 17:04 UTC, CruuzAzul commented on src/data/compositionsList.ts
Est ce que l'on split pas direct ce fichier en plusieurs pour éviter le fichier de 4000 lignes ?

2023-07-04 17:04 UTC, CruuzAzul commented on src/data/sideBarConfig.ts
> +		items: (categoryProps | videoProps)[] | videoProps[];
```suggestion
		items: (categoryProps | videoProps)[];
```

2023-07-04 17:04 UTC, CruuzAzul commented on styles/app/components/sidebar/activeLink.module.css
> +	}
```suggestion
	&:hover,
    &.active {
	    background: var(--switch-background);
    }
```

2023-07-04 17:04 UTC, CruuzAzul commented on styles/app/components/sidebar/nav.module.css
> +						)
On a pas ce linear gradient de partout dans l'app en dupliquer ?

2023-07-05 09:11 UTC, Boyadjie commented on src/app/components/sidebar/CompositionThumbnail.tsx
> +						/>
ouais je suis d'accord, j'ai regardé les still mais c'est un élément remotion, le plus opti serais d'avoir des screenshots mais je sais pas trop comment on peut les générer à l'a volée...

2023-07-05 09:19 UTC, Boyadjie commented on src/data/compositionsList.ts
On peut faire un fichier de config par video et dans ce fichier on regroupe tout ?

On aurais une structure dans data du style:
/data
- /config
	- sidebarConfig.ts
	- compositionsConfig.ts
	- /templates
		- talkConfig.ts
		...
	-/showcases
		...
		
Et dans compositionConfig on fait le json en important les config

2023-07-05 12:37 UTC, Boyadjie commented on src/data/compositionsList.ts
> +		| TouraineTechProps
J'ouvre une us

2023-07-05 13:09 UTC, Boyadjie commented on src/data/compositionsList.ts
> +import {staticFile} from 'remotion';
Je fait une us

2023-07-05 13:31 UTC, Boyadjie commented on styles/app/components/sidebar/nav.module.css
> +						)
Il est dupliqué 3 fois oui, je fait une variable 👍

2023-07-05 13:54 UTC, CruuzAzul commented on src/data/compositionsList.ts
On peut essayer ça go

2023-07-05 14:10 UTC, Slocaly commented on styles/app/components/sidebar/sidebar.module.css
> +		padding: 15px 20px 20px 20px;
Tu peux le remplacer par ça 

```suggestion
		padding: 15px 20px 20px;
```

Cela correspond à `padding: left y right`

2023-07-05 14:10 UTC, Slocaly commented on styles/app/components/sidebar/sidebar.module.css
> +		padding: 20px 20px 15px 20px;
Tu peux le remplacer par ça

```suggestion
		padding: 20px 20px 15px;
```

Cela correspond à `padding: left y right`

2023-07-07 09:48 UTC, CruuzAzul approved these changes

2023-07-07 09:48 UTC, CruuzAzul commented on src/app/hooks/useCompositionConfig.ts
> +		)}`;
Ça c'est bizarre d'avoir les millisecondes dans l'affichage, et en plus on a pas l'unité de mesure

2023-07-07 10:00 UTC, Boyadjie commented on src/app/hooks/useCompositionConfig.ts
> +		)}`;
Ouais j'ai fait comme sur les wireframe mais @Slocaly trouvais qu'on pouvais limite s'en passer t'en pense quoi ?
Si on le garde du coup on fait quoi ? on rajoute l'unité ?

2023-07-07 11:19 UTC, merged