feat(app): layout responsive with sidebar right
lyonjs/shortvid.io pull request #442
Opened 2023-07-24 12:29 UTC by Boyadjie

## 🤔 Why do you want to make those changes?

To have a better UX/UI experience for mobile users

## 🧑‍🔬 How did you make them?

I added some style and components to the pages

## 🧪 How to check them?

- check the code
- check the preview

2023-07-24 16:34 UTC, CruuzAzul commented
Je me demande si il faut pas passer sur un breakpoint supérieur pour passer en vue responsive, tu en penses quoi ?

2023-07-27 08:26 UTC, Slocaly requested changes

2023-07-27 08:26 UTC, Slocaly commented on src/app/forms/Form.tsx
> +export type formConfigProps = {
```suggestion
export type FormConfigProps = {
```

2023-07-27 08:26 UTC, Slocaly commented on src/app/forms/Form.tsx
> +				{Object.keys(formConfig).map((value) => {
Tu as une autre fonction de `Object` qui te permet d'avoir directement les valeurs, et qui te permet donc de supprimer la ligne 37

2023-07-27 08:38 UTC, CruuzAzul approved these changes

2023-07-27 08:38 UTC, CruuzAzul commented on app/templates/layers/layers/page.tsx
> +						</button>
On peut faire un composant pour ça, on va surement s'en servir pour Devfest Nantes 😊 Faut pas que ça soit lié à `Layers` dans le nom mais c'est plus un truc pour du render en full screen

2023-07-27 12:47 UTC, Boyadjie commented on app/templates/events/event/page.tsx
> +						<FontPicker label="Font family" />
ça nécessitera un refacto dans une autre vu que dans la config on prend des `setState: (event) => void` et pour ce composant la on a un `setState: (string) => void`

2023-07-27 13:24 UTC, Slocaly approved these changes

2023-07-27 13:42 UTC, merged