fix(sidebar): resize
lyonjs/shortvid.io pull request #466
Opened 2023-07-28 14:28 UTC by Boyadjie

## 🤔 Why do you want to make those changes?

To fix the bug when folding the sidebar the width stay the same

## 🧑‍🔬 How did you make them?

updated a variable name that was forgotten.

## 🧪 How to check them?

check code

2023-07-28 15:12 UTC, CruuzAzul requested changes

2023-07-28 15:12 UTC, CruuzAzul commented on styles/app/components/sidebar/nav.module.css
> +	overflow-y: scroll;
Je vois pas pourquoi on fait pas juste un `overflow: scroll`

2023-07-31 06:29 UTC, Boyadjie commented on styles/app/components/sidebar/nav.module.css
> +	overflow-y: scroll;
Ba... pour pas avoir la barre de scroll en bas... 
<img width="687" alt="image" src="https://github.com/lyonjs/shortvid.io/assets/72607059/8d522e64-c3a8-4c7e-91fb-bbb0818a2686">

2023-07-31 06:55 UTC, CruuzAzul commented on styles/app/components/sidebar/nav.module.css
> +	overflow-y: scroll;
`overflow: auto` pardon 😅

2023-07-31 07:13 UTC, Boyadjie commented on styles/app/components/sidebar/nav.module.css
> +	overflow-y: scroll;
ha, parce que quand la barre apparait ça fait un décalage

2023-07-31 09:55 UTC, Slocaly approved these changes

2023-07-31 13:02 UTC, merged